# Generated by Django 4.1.3 on 2022-11-12 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcer2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondencia',
            name='Numero_pedido',
            field=models.CharField(default=4785, max_length=90),
            preserve_default=False,
        ),
    ]
