# Generated by Django 4.1.3 on 2022-11-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcer2', '0002_correspondencia_numero_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondencia',
            name='fecha_entrega',
            field=models.DateField(verbose_name='Fecha de recepción'),
        ),
    ]
