# Generated by Django 4.1.3 on 2022-11-13 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcer2', '0003_alter_correspondencia_fecha_entrega'),
    ]

    operations = [
        migrations.CreateModel(
            name='Residencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('dueño', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('Correo', models.CharField(max_length=50)),
            ],
        ),
    ]
