# Generated by Django 4.1.3 on 2022-11-13 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcer2', '0004_residencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='correspondencia',
            old_name='Numero_pedido',
            new_name='destinatario',
        ),
        migrations.AddField(
            model_name='correspondencia',
            name='Conserje',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='correspondencia',
            name='direccion',
            field=models.CharField(max_length=50),
        ),
    ]
