# Generated by Django 4.1.3 on 2022-11-13 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcer2', '0005_rename_numero_pedido_correspondencia_destinatario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondencia',
            name='direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcer2.residencia'),
        ),
    ]
